/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 19 05:04:43 GMT 2024
 */

package cs4218.impl.apps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cs4218.impl.apps.EchoApplicationImpl;
import java.io.BufferedOutputStream;
import java.io.OutputStream;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EchoApplicationImpl_ESTest extends EchoApplicationImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockFile mockFile0 = new MockFile("QNw[.6S ]");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      BufferedOutputStream bufferedOutputStream0 = new BufferedOutputStream(mockFileOutputStream0);
      EchoApplicationImpl echoApplicationImpl0 = new EchoApplicationImpl(bufferedOutputStream0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EchoApplicationImpl echoApplicationImpl0 = new EchoApplicationImpl((OutputStream) null);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      // Undeclared exception!
      try { 
        echoApplicationImpl0.run(linkedList0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/io/IOUtils
         //
         verifyException("cs4218.impl.apps.EchoApplicationImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EchoApplicationImpl echoApplicationImpl0 = new EchoApplicationImpl((OutputStream) null);
      // Undeclared exception!
      try { 
        echoApplicationImpl0.run((List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }
}
